### ISSUE TITLE
Could not set SSL Certificate - website bindings

### ISSUE THREAD

**Issue by lukee8** [PowerShellOrg/cWebAdministration#14]
I'm trying to set SSL cert to a website bindings. 
In event log there is error:
This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on PSHOrg_cWebsite DSC resource. FullyQualifiedErrorId is WebBindingCertifcateError,UpdateBindings. ErrorMessage is Failure to add certificate to web binding..

and:
This event indicates that failure happens when LCM is processing the configuration. ErrorId is 0x1. ErrorDetail is The SendConfigurationApply function did not succeed.. ResourceId is [cWebsite]WebsiteName1 and SourceInfo is D:\Users\Herman\TestPlatformProvisioning.ps1::203::3::cWebsite. ErrorMessage is The PowerShell DSC resource PSHOrg_cWebsite threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details

Bindings configuration looks:
@(PSHOrg_cWebBindingInformation
	{
		Protocol				= "HTTPS"
		Port					= 443
		CertificateThumbprint	= 'D464CB097A9E7F9B2AFD8896C914841562FF4B79'
		CertificateStoreName	= "Personal"
	}
)

Certificate is installed on server in Personal store, I can choose it manually from GUI.
Am I doing anything wrong, or it's simply not working in actual version?

**Comment by dlwyatt** [comment]
Try changing your CertificateStoreName value from "Personal" to "My", and see if that works.  ("Personal" is a localized name for that store; in the API, it's referred to as "My".)

**Comment by lukee8** [comment]
Only Personal and WebHosting are in ValueMap...

PSHOrg_cWebsite.schema.mof:
"[write,ValueMap{"Personal", "WebHosting"},Values{"Personal", "WebHosting"}] string CertificateStoreName;"

**Comment by dlwyatt** [comment]
Hmm, let me have a closer look at the code.

**Comment by dlwyatt** [comment]
Looks like this is a bug that exists in the original xWebAdministration module; that part of the code hasn't changed yet in our fork.  I'll get it sorted out soon.

The acceptable value in the schema will change from 'Personal' to 'My' (which should not be a breaking change since the code is already broken; the only way anyone could have gotten that working before was to create a second store actually named "Personal", and to place the cert in there.)  I'll also be adding some more user-friendly error messages when the certificate does not exist in the specified location, or doesn't have a private key.

**Comment by dlwyatt** [comment]
Should be fixed now; pull the latest code from the master branch, and leave the store name set to "My" in your configuration.

**Comment by lukee8** [comment]
Thank you. It's working now :)
